language: php
php:
    - '7.1'
before_script: 
    - cp bin/config/parameters.yml.dist bin/config/parameters.yml
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:create --env=test
    - php bin/console doctrine:fixtures:load -n --env=test
    - composer install
services:
    - mysql
script:
    - vendor/bin/phpcs -p --standard=Symfony2 --extensions=php ./src
