# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.profile:
        class: AppBundle\Form\Type\ProfileType
        tags:
            - {name: form.type, alias: app_user_profile}

    app.form.registration:
        class: AppBundle\Form\Type\RegistrationType
        tags:
            - {name: form.type, alias: app_user_registration }
    user_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\User
    filter:
        class: AppBundle\Services\TrainersFilter
        arguments: ['@user_repository']
    average:
        class: AppBundle\Services\RatingAverager
        arguments: ['']
